name: gspufrn
description: Projeto para desenvolvimento de funcionalidades da disciplina de GSP3.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  zoom_widget: ">=0.1.3"
  scoped_model: ^1.0.1
  crypto: ">=2.1.5"
  chips_choice: ">=1.2.0"
  random_color: ">=1.0.5"
  font_awesome_flutter: ">=8.8.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/ufrn.png
    - images/dep.png

